### PR TITLE
fix sepBy and sepBy1

### PR DESCRIPTION
**Pull request by sledorze**

### CODE REVIEW

**Comment by gcanti** [comment]
Hi @sledorze, thanks! 

I totally misread the source of `sepBy1` (link below)

[sepBy](https://github.com/bodil/purescript-eulalie/blob/master/src/Data/Eulalie/Parser.purs#L163)

[sepBy1](https://github.com/bodil/purescript-eulalie/blob/master/src/Data/Eulalie/Parser.purs#L169)

I'd love to be more adherent as possible to the original version in PureScript if possible, what about this implementation?

```ts

// this is the implementation of *> that you can find here
// https://github.com/purescript/purescript-prelude/blob/master/src/Control/Apply.purs#L56

// we could add it to fp-ts (!)

// TODO remove this when applySecond lends in fp-ts
/** Combine two effectful actions, keeping only the result of the second. */
function applySecond<F extends HKTS>(apply: StaticApply<F>): <A, B>(fa: HKT<A>[F], fb: HKT<B>[F]) => HKT<B>[F] {
  return <A, B>(fa: HKT<A>[F], fb: HKT<B>[F]) => apply.ap<B, B>(apply.map(() => identity, fa), fb)
}

// now this should be a 1-to-1 translation of the original

/** Matches the provided parser `p` one or more times, but requires the
 * parser `sep` to match once in between each match of `p`. In other words,
 * use `sep` to match separator characters in between matches of `p`.
 */
export function sepBy1<A, B>(sep: Parser<A>, parser: Parser<B>): Parser<NonEmptyArray<B>> {
  return parser.chain(head => alt(many(new Parser<B>(s => {
    return applySecond({ URI, map, ap })<A, B>(sep, parser).run(s)
  })), of([])).chain(tail => of(new NonEmptyArray<B>(head, tail))))
}
```

`sepBy` should be already ok with this implementation

**Comment by sledorze** [comment]
@gcanti Ok for keeping as close as possible to the original version.
I think we need to create a combinator to replace the missing infix operator to keep things lean.

Something like:

```
export function second<A, B>(pa: Parser<A>, pb: Parser<B>): Parser<B> {
  return new Parser(s =>
    applySecond({ URI, map, ap })<A, B>(pa, pb).run(s)
  )
}

export function sepBy1<A, B>(sep: Parser<A>, parser: Parser<B>): Parser<NonEmptyArray<B>> {
  return parser.chain(head => alt(many(second(sep, parser)), of([])).chain(tail => of(new NonEmptyArray(head, tail))))
}


```

**Comment by gcanti** [comment]
LGTM

**Comment by sledorze** [comment]
Where do you get your identity definition from?
the one form fp-ts 

`import { identity } from 'fp-ts';`

Does not make it typecheck..

**Comment by gcanti** [comment]
```ts
import { Predicate, identity } from 'fp-ts/lib/function'
```

**Comment by gcanti** [comment]
`import { identity } from 'fp-ts';` is the `Identity` module

**Comment by gcanti** [comment]
Patch release on its way..

**Pull request merged**
